### ISSUE TITLE
disallow or warn when lab.before not used inside lab.experiment?

### ISSUE THREAD

**Issue by hulbert** [hapijs/lab#409] opened 2015-07-22 07:34 UTC
Internally we had someone write a file something like this:

``` js
lab.before(function(done) {
    // do something
    done()
})

lab.experiment('group of tests', function() {
    lab.test('it works', function(done) {
         // tests
         done()
    })
})
```

Glancing over, this looks okay. However if the before times out or has some error (like done() called twice as it did in our case) then there is no experiment name to explain where the before fails so you get something like "Before ____ timed out". It would be great if using `lab.before` in this way triggered some error or at least a warning, since it can be difficult to debug the origin of an error in a before without an experiment name.

**Comment by hueniverse** [comment] 2015-07-22 08:15
The problem is there is always an implicit experiment context set.

**Comment by geek** [comment] 2018-11-09 23:55
Closing, as this has been open for a few years and it doesn't appear like we will get to it.

**Closed by geek** 2018-11-09 23:55 UTC
Labels: request
