### ISSUE TITLE
using with massive

### ISSUE THREAD

**Issue by jney** [hapijs/lab#564] opened 2016-04-20 09:20 UTC
I'm using `lab` with [massive](https://github.com/robconery/massive-js).
Using `connectSync` all the tests are skipped. Any idea why ?

**Comment by Marsup** [comment] 2016-04-20 09:29
What do you mean skipped ? Lab is showing them as skipped or you see nothing ?

**Comment by jney** [comment] 2016-04-20 09:40
I meant that i don't see any output, but process status looks fine `$ echo $? # 0`

**Comment by Marsup** [comment] 2016-04-20 09:44
This might be caused by `deasync`, which seems like a pretty ugly way to achieve their goal.

**Comment by jney** [comment] 2016-04-20 09:47
seems to be a good way to look. any idea how to fix it ?

**Comment by Marsup** [comment] 2016-04-20 09:52
Why do you need it sync ? Can't it be async in a before ?

**Comment by jney** [comment] 2016-04-20 09:55
because i'd rather have a global db variable, instead using callbacks.
but if i have no choice, i'd adapt my code.

**Comment by Marsup** [comment] 2016-04-20 10:13
That's worth making a small test just to ensure it's the culprit, don't change all your code yet.

**Comment by jney** [comment] 2016-04-20 10:38
Massive connection is a singleton so i made this approach.

```js
'use strict'
​
const Massive = require('massive')
​
let DB
​
Massive.connect({connectionString: process.env.DATABASE_URL}, (err, db) => {
  if (err) throw err
  DB = db
})
​
module.exports = class Payment {
  static create (opts, fn) {
    return DB.my_table.save(opts, (err, o) => {
      if (err) return fn(err)
      fn(null, o)
    })
  }
}
```

Even using this method `DB` is not ready when called with `lab`.

**Comment by Marsup** [comment] 2016-04-20 10:55
Welcome in the asynchronous world :) As I told you don't modify your code, make a simple test with lab doing an async connection in a before and see if it crashes, then do the same with sync, if it only crashes in sync, we'll know that's the problem.

**Comment by jney** [comment] 2016-04-20 11:55
> Welcome in the asynchronous world :) 

Yes, the previous code is dirty. But, as i told before `massive` connection instance is a singleton, which i want to share in each of my models. I don't want/need to call the following code each time, i request my db:

    Massive.connect({connectionString: process.env.DATABASE_URL}, (err, db) => {
      db // i want this object in each of my models.
    })
​
`connectSync` is the matching approach for what i want, but fail with `lab`

What pattern should i use to share `db` ?

**Comment by Marsup** [comment] 2016-04-20 12:13
Once again, I'm not telling you you shouldn't, I just want to know if the synchronous version is causing this.

**Comment by jney** [comment] 2016-04-20 14:10
sorry Nicolas, i thought i was clear about this. Using `Massive.connectSync` makes `lab` exit prematurely, without any output.

```
$ ./node_modules/.bin/gulp test
[16:08:44] Using gulpfile ~/path/to/my/project/gulpfile.js
[16:08:44] Starting 'test'...
before
[16:08:44] Finished 'test' after 682 ms
```

```js
const Massive = require('massive')
console.log('before')
const DB = Massive.connectSync({connectionString: process.env.DATABASE_URL})
console.log('after') // this is never reached
module.exports = DB
```

**Comment by Marsup** [comment] 2016-04-20 14:25
Could you try without gulp involved ? I know I had issues with gulp forcefully exiting before logging could happen.

**Comment by jney** [comment] 2016-04-20 14:47
yes i did it. same result.

```
$ ./node_modules/.bin/lab
before

```

**Comment by Marsup** [comment] 2016-04-20 14:50
Still exit code 0 ? Could you post a full gist so that I can reproduce ?

**Comment by jney** [comment] 2016-04-20 15:16
https://gist.github.com/jney/f583d795aca0a4fc73c26dee39d73695

**Comment by Marsup** [comment] 2016-04-20 15:35
In your gist this is a normal exit caused by https://github.com/hapijs/lab/blob/master/lib/reporters/index.js#L107. I thought this would be enough to let the console drain, maybe not. Thoughts @geek ? setTimeout on that exit ?

**Comment by geek** [comment] 2016-04-20 15:51
@Marsup we can test with a `setImmediate` or `setTimeout` on the exit.

**Comment by Marsup** [comment] 2016-04-20 16:04
Many issues about it on the node repo, I don't think setImmediate will be enough, we need to let node and the OS flush, that sucks but I don't see another way than arbitrary bigish timeout.

**Comment by IsaiahJTurner** [comment] 2016-08-23 21:00
Ran into this issue myself. Ended up using connectSync.

**Comment by geek** [comment] 2017-06-20 02:15
@IsaiahJTurner this should be fixed with the latest https://github.com/hapijs/lab/blob/a5e2074887c61e65e0e11dd33ef3f1a4614d65f2/lib/reporters/index.js#L115

**Closed by geek** 2017-06-20 02:15 UTC
Labels: non-issue
