### ISSUE TITLE
Very simple route is throwing "return outside function" (espree/acorn) error when loading module for coverage (with no linting requested)

### ISSUE THREAD

**Issue by jcollum** [hapijs/lab#694] opened 2017-03-28 16:55 UTC
#### Are you sure this is an issue with hapi or are you just looking for some help?

[I posted this on /discuss](https://github.com/hapijs/discuss/issues/462) and got no feedback. The issue went away but now it's back. The error is so cryptic that I'm at a loss for how to figure out what the actual issue is. 

#### What are you trying to achieve or the steps to reproduce?

I'm trying to run coverage on a simple route: 

```js
"use strict";
// Note: this shared object is used across all tests 
// and is *not* failing in all of them, so I doubt this is the issue
const {logger, config} = require(require('path').join(process.cwd(), 'src', 'shared'));

const healthRoute = {
  method: 'GET',
  path: '/health',
  config: {
    description: "Health route"
  },
  handler: function(req, reply) {
    logger.trace("Health route.");
    reply({status: "UP", hostName: config.hostName, version: config.version});
  }
};

module.exports = [healthRoute];

```

Test line (`-L` (linting) is not present)): 
```
$ cat package.json | grep "test" 
    "test": "lab -lv -e development -t 80 -r console --coverage-exclude test test/unit",
```

Adding linter options: `--lint-options '{"globalReturn":true}'` made no difference. 

Result: 

```
{ SyntaxError: 'return' outside of function
    at Parser.instance.raise.instance.raiseRecoverable (/Users/collumj/work/dda/front-porch-validator/node_modules/espree/espree.js:439:19)
    at Parser.pp$1.parseReturnStatement (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:876:10)
    at Parser.pp$1.parseStatement (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:734:32)
    at Parser.pp$1.parseBlock (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:1026:23)
    at Parser.pp$1.parseStatement (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:744:31)
    at Parser.pp$1.parseIfStatement (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:870:46)
    at Parser.pp$1.parseStatement (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:733:28)
    at Parser.pp$1.parseTopLevel (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:658:23)
    at Parser.parseTopLevel (/Users/collumj/work/dda/front-porch-validator/node_modules/espree/espree.js:301:34)
    at Parser.parse (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:528:15)
    at Object.parse (/Users/collumj/work/dda/front-porch-validator/node_modules/acorn/dist/acorn.js:3357:37)
    at Object.parse (/Users/collumj/work/dda/front-porch-validator/node_modules/espree/espree.js:738:21)
    at Object.internals.instrument (/Users/collumj/work/dda/front-porch-validator/node_modules/lab/lib/coverage.js:238:25)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/collumj/work/dda/front-porch-validator/node_modules/lab/lib/coverage.js:31:55)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module._load (/Users/collumj/work/dda/front-porch-validator/node_modules/mock-require/index.js:23:22)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/collumj/work/dda/front-porch-validator/src/shared.js:3:105)
    at Module._compile (module.js:570:32)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/collumj/work/dda/front-porch-validator/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module._load (/Users/collumj/work/dda/front-porch-validator/node_modules/mock-require/index.js:23:22)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/collumj/work/dda/front-porch-validator/src/routes/index.js:2:121)
    at Module._compile (module.js:570:32)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/collumj/work/dda/front-porch-validator/node_modules/lab/lib/coverage.js:31:36)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module._load (/Users/collumj/work/dda/front-porch-validator/node_modules/mock-require/index.js:23:22)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at buildServer (/Users/collumj/work/dda/front-porch-validator/test/unit/allRoutes.js:23:15)
    at exc (/Users/collumj/work/dda/front-porch-validator/test/unit/allRoutes.js:44:15)
    at it (/Users/collumj/work/dda/front-porch-validator/test/unit/allRoutes.js:56:13)
    at Immediate.setImmediate (/Users/collumj/work/dda/front-porch-validator/node_modules/lab/lib/runner.js:674:36)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) index: 448, lineNumber: 20, column: 3 }

```

I can post the full test code if needed, but it seems wasteful. All it's really doing is attaching the route to a server: 

```js
const buildServer = (routeName, cb) => {
  server = new Hapi.Server();
  let route = require(path.join(process.cwd(), "src", "routes", routeName));
  server.connection();
  server.route(route[0]);
  server.start(() => {
    cb(server);
  });
};
```

The relevant (possibly) lines from mock-require/index.js: 

```
  return mockExports.hasOwnProperty(fullFilePath)
    ? mockExports[fullFilePath]
    : originalLoader.apply(this, arguments);
```

#### What was the result you received?

Got an error: "'return' outside function" 

#### What did you expect?

A route that loads and runs fine shouldn't be throwing any linter errors when running coverage without linting options turned on. 

#### Context
```
$ node_modules/.bin/lab --version 
13.0.1

$ versions
npm 3.10.10
node v6.10.0
OS:
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```

**Comment by geek** [comment] 2017-03-29 15:39
@jcollum are you able to include the shared/config folders/files. Another possibility is to create a repo with the relevant bits. At the moment I cannot get the example to run without the shared folder.

**Comment by jcollum** [comment] 2017-03-29 15:43
The logger is just a bunyan logger and the config is a convict config. But as noted, it's not causing any of the other tests it's used in to fail. 

Unfortunately I no longer have access to this code -- layoffs about an hour after I posted that. doh!

Question: it looks like lab is using espree to load the module even if linting is not requested. Is that right? Is that expected behavior?

**Comment by geek** [comment] 2017-03-29 15:53
@jcollum sorry to hear that. Espree is used on the code coverage side.

**Comment by jcollum** [comment] 2017-03-29 15:54
It seems like espree is throwing linter errors when I'm not passing in `-L` but I am passing in `-t 80`.

**Comment by geek** [comment] 2017-04-13 16:01
@jcollum are you able to include any of the shared files to help with reproducing the issue?

**Comment by geek** [comment] 2017-04-13 16:03
@jcollum I am closing for now as I cannot reproduce/run the provided code. Please reopen if you can provide an example. In the meantime I will keep trying to reproduce and will keep an eye out for the potential bug.

**Closed by geek** 2017-04-13 16:03 UTC

**Comment by jcollum** [comment] 2017-04-13 16:37
Understandable. I'll come back to this if it happens again.

**Comment by fiacc** [comment] 2017-12-02 02:06
@geek I ran in to this and reproduced https://github.com/fiacc/return-error  . If there's a return in the module espree complains.

**Comment by jcollum** [comment] 2017-12-02 03:53
Wow @fiacc ima call you Necromancer now
